import './globals.css'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//context provider
import { SearchContextProvider } from '@/context/search'

export default function RootLayout({ children }) {
  return (
    <SearchContextProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </SearchContextProvider>
  )
}
